# Pre-commit hooks configuration
# See https://pre-commit.com for more information
repos:
  # General file formatting and checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json

  # Terraform formatting
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.1
    hooks:
      - id: terraform_fmt
        name: Terraform format
        description: Rewrites all Terraform configuration files to a canonical format.
        files: (\.tf|\.tfvars)$
        exclude: \.terraform/

  # Prettier for TypeScript, JavaScript, JSON, CSS, and Markdown
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Format with Prettier
        exclude: |
          (?x)^(
            \.terraform/.*|
            node_modules/.*|
            .*\.snap|
            pnpm-lock\.yaml|
            package-lock\.json
          )$
