formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  {{ if .Config.Modules -}}
  ## Modules

  {{ range .Config.Modules -}}
  - {{ .Name }}: {{ .Source }}{{ if .Version }} ({{ .Version }}){{ end }}
  {{ end }}
  {{ end }}

  {{ if .Requirements -}}
  ## Requirements

  {{ .Requirements }}
  {{ end }}

  {{ if .Providers -}}
  ## Providers

  {{ .Providers }}
  {{ end }}

  {{ if .Resources -}}
  ## Resources

  {{ .Resources }}
  {{ end }}

  {{ if .Inputs -}}
  ## Inputs

  {{ .Inputs }}
  {{ end }}

  {{ if .Outputs -}}
  ## Outputs

  {{ .Outputs }}
  {{ end }}

  {{ .Footer }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
